#!/bin/sh
while read -r file
do
    case "$1" in
    "k")
        kdeconnect-cli --refresh && kdeconnect-cli --device 415a811582e4a899 --share "$file" || notify-send -u low "send failed" & ;;
    "v")
        setsid -f mpv "$file" -quiet >/dev/null 2>&1 ;;
    "w")    setbg "$file" ;;
    "r")
        name="$(dmenu -p "rename $file to: ")" 2> /dev/null
        if ! [ -z "$name" ]; then
            #mv "$file" "$name"
            mv "$file" "$(dirname $file)/$name"
        fi
        ;;
    "c")
        [ -z "$destdir" ] && destdir="$(sed "s/#.*$//;/^\s*$/d" ${XDG_CONFIG_HOME:-$HOME/.config}/shell/bm-dirs | awk '{print $2}' | dmenu -l 20 -i -p "Copy file(s) to where?" | sed "s|~|$HOME|g")"
        [ ! -d "$destdir" ] && notify-send "$destdir is not a directory, cancelled." && exit
        cp "$file" "$destdir" && notify-send -i "$(readlink -f "$file")" "$file copied to $destdir." &
        ;;
    "m")
        [ -z "$destdir" ] && destdir="$(sed "s/\s.*#.*$//;/^\s*$/d" ${XDG_CONFIG_HOME:-$HOME/.config}/shell/bm-dirs | awk '{print $2}' | dmenu -l 20 -i -p "Move file(s) to where?" | sed "s|~|$HOME|g")"
        [ ! -d "$destdir" ] && notify-send "$destdir is not a directory, cancelled." && exit
        mv "$file" "$destdir" && notify-send -i "$(readlink -f "$file")" "🚚 $file moved to $destdir." &
        ;;
	"h")
		convert -rotate 90 "$file" "$file" ;;
	"l")
		convert -rotate -90 "$file" "$file" ;;
	"f")
		convert -flop "$file" "$file" ;;
	"y")
		printf "%s" "$file" | tr -d '\n' | xclip -selection clipboard &&
		notify-send "$file copied to clipboard" & ;;
	"Y")
		readlink -f "$file" | tr -d '\n' | xclip -selection clipboard &&
	    notify-send "$(readlink -f "$file") copied to clipboard" & ;;
	"d")
		[ "$(printf "No\\nYes" | dmenu -i -p "Really delete $file?")" = "Yes" ] && rm "$file" && notify-send "$file deleted." ;;

	"D")
		[ "$(printf "No\\nYes" | dmenu -i -p "Really shred $file?")" = "Yes" ] && shred -uvzn3 "$file" && notify-send "$file shreded." ;;

	"g")	ifinstalled gimp && setsid -f gimp "$file" ;;
	"i")	notify-send "File information" "$(mediainfo "$file")" ;;
        "o")
            name=$(echo ${file%.*})
            setsid -f mpv "$name.webm" -quiet >/dev/null 2>&1
            setsid -f mpv "$name.mkv" -quiet >/dev/null 2>&1 ;;
esac
done
