#!/bin/sh

[ -x "$(command -v nvim)" ] && alias vim="nvim" vimdiff="nvim -d"

# Use $XINITRC variable if file exists.
[ -f "$XINITRC" ] && alias startx="startx $XINITRC"

# sudo not required for some system commands
for command in mount umount updatedb su ; do
	alias $command="sudo $command"
done; unset command

urlencode () {
    declare str="$*"
    declare encoded=""
    declare i c x
    for ((i = 0; i<${#str}; i++)); do
        c=${str:$i:1}
        case "$c" in
            [-_.~~a-zA-Z0-9] ) x="$c" ;;
            * ) printf -v x '%%%02x' "'c$" ;;
        esac
        encoded+="$x"
    done
    echo "$encoded"
}
duck () {
    declare url=$(urlencode "$*")
    lynx  "https://duckduckgo.com/lite?q=$url"
}

alias \
    "?"=duck \
    config='/usr/bin/git --git-dir=$HOME/.dotfiles/ --work-tree=$HOME' \
    g='git' \
    p="pacman" \
    P="sudo pacman" \
    ll="ls -l --color=auto" \
    emacsc="emacsclient  -c -a 'emacs'" \
    Tmux="tmux a || tmux" \
    abook="abook -C $XDG_CONFIG_HOME/abook/abookrc --datafile $XDG_CONFIG_HOME/abook/addressbook" \
    cp="cp -iv" \
    mv="mv -iv" \
    rm="rm -vI" \
    bc="bc -lq" \
    mkd="mkdir -pv" \
    ytfzff="ytfzf -t --thumbnail-quality=1" \
    yt="yt-dlp --external-downloader aria2c --add-metadata -ic -P $XDG_VIDEOS_DIR/yt " \
    yta="yt-dlp --remux-video ogg -f bestaudio/best --external-downloader aria2c -P $XDG_MUSIC_DIR " \
    aria2c="aria2c --auto-file-renaming=false" \
    ffmpeg="ffmpeg -hide_banner" \
    ls="ls -hN --color=auto --group-directories-first" \
    grep="grep --color=auto" \
    diff="diff --color=auto" \
    ip="ip -color=auto" \
    nf="notify-send " \
    kd="/usr/lib/kdeconnectd && kdeconnect-cli --refresh ; kdeconnect-indicator&" \
    kdend="killall kdeconnectd kdeconnect-indicator&" \
    lsall='find . -type f -printf "%t@ %p\n" | sort -nr | cut -d\  -f2-' \
    ka="killall" \
    trem="transmission-remote" \
    z="zathura" \
    ref="shortcuts >/dev/null; source $XDG_CONFIG_HOME/shell/shortcutrc; source $XDG_CONFIG_HOME/shell/aliasrc" \
    # random_password="date +%s | sha256sum | base64 | head -c 15 ; echo" \
