#!/bin/sh

[ -x "$(command -v nvim)" ] && alias vim="nvim" vimdiff="nvim -d"

# Use $XINITRC variable if file exists.
[ -f "$XINITRC" ] && alias startx="startx $XINITRC"

# sudo not required for some system commands
for command in mount umount updatedb su ; do
	alias $command="sudo $command"
done; unset command

alias config='/usr/bin/git --git-dir=$HOME/.dotfiles/ --work-tree=$HOME'

urlencode () {
    declare str="$*"
    declare encoded=""
    declare i c x
    for ((i = 0; i<${#str}; i++)); do
        c=${str:$i:1}
        case "$c" in
            [-_.~~a-zA-Z0-9] ) x="$c" ;;
            * ) printf -v x '%%%02x' "'c$" ;;
        esac
        encoded+="$x"
    done
    echo "$encoded"
}

duck () {
    declare url=$(urlencode "$*")
    lynx  "https://duckduckgo.com/lite?q=$url"
}

yta () {
    yt-dlp --remux-video ogg -f bestaudio/best --external-downloader aria2c -P $(find $XDG_MUSIC_DIR -maxdepth 2 -type d | fzf) $@
}

yt () {
    yt-dlp -f 22 --external-downloader aria2c --add-metadata -ic -P $(find $XDG_VIDEOS_DIR -maxdepth 2 -type d | fzf) $@
}

configa(){
    get_unstaged_file(){
        # only show unstaged files
        # "^M" are added, "^MM" are added but have modifications to be added, while "^ M are not added"
        unstaged_file="$HOME/$(config status --porcelain | grep -E "(^ M|^MM)" | awk '{print $2}' | fzf)"
    }

    get_unstaged_file || return 1

    config diff "$unstaged_file" &&
    config add "$unstaged_file" &&
    config status &&
    echo "Type our commit message, or press 'n' to leave?"
    read -r ans
    [ "$ans" != "n" ] && config commit -m "$ans"
}

alias \
    g='git' \
    d="dragon-drop" \
    p="pacman" \
    P="sudo pacman" \
    ll="ls -l --color=auto" \
    emacsc="emacsclient  -c -a 'emacs'" \
    Tmux="tmux a || tmux" \
    abook="abook -C $XDG_CONFIG_HOME/abook/abookrc --datafile $XDG_CONFIG_HOME/abook/addressbook" \
    cp="cp -iv" \
    mv="mv -iv" \
    rm="rm -vI" \
    bc="bc -lq" \
    mkd="mkdir -pv" \
    Yt="yt-dlp --external-downloader aria2c --add-metadata -ic" \
    ref="shortcuts >/dev/null; source $XDG_CONFIG_HOME/shell/shortcutrc" \
    aria2c="aria2c --auto-file-renaming=false" \
    ffmpeg="ffmpeg -hide_banner" \
    ls="ls -hN --color=auto --group-directories-first" \
    grep="grep --color=auto" \
    diff="diff --color=auto" \
    ip="ip -color=auto" \
    nf="notify-send " \
    ka="killall" \
    trem="transmission-remote" \
    z="zathura" \
