#!/bin/zsh

#functions path
fpath+=("$ZDOTDIR/functions")
export JAVA_HOME=/usr/lib/jvm/default
export GOPATH="$XDG_DATA_HOME/go"
export CARGO_HOME="$XDG_DATA_HOME/cargo"
export NPM_PATH="$XDG_DATA_HOME/npm"

export PATH="$PATH:${$(find ~/.local/bin -type d -printf %p:)%%:}":$NPM_PATH/bin:$GOPATH/bin:$CARGO_HOME/bin:"$JAVA_HOME/bin"

unsetopt PROMPT_SP

# Default programs:
export EDITOR="nvim"
export TERMINAL="st"
export BROWSER="firefox"
export VIDEO="mpv"
export IMAGE="nsxiv"

export CM_SELECTIONS="clipboard"
export CM_DEBUG=1
export CM_OUTPUT_CLIP=1
export CM_MAX_CLIPS=50

export STUFF="$HOME/stuff"
export XDG_DOWNLOAD_DIR="$STUFF"
export XDG_MUSIC_DIR="$STUFF/music"
export XDG_VIDEOS_DIR="$STUFF/videos"
export XDG_PICTURES_DIR="$STUFF/pictures"
export XDG_DOCUMENTS_DIR="$STUFF/documents"
export NOTES_DIR="$HOME/personal/notes"
export XDG_CONFIG_HOME="$HOME/.config"
export XDG_DATA_HOME="$HOME/.local/share"
export XDG_CACHE_HOME="$HOME/.cache"
export XRESOURCES="$XDG_CONFIG_HOME/x11/xresources"
export XINITRC="$XDG_CONFIG_HOME/x11/xinitrc"
export XSESSION="$XDG_CONFIG_HOME/x11/xsession"
export XAUTHORITY="$XDG_RUNTIME_DIR/Xauthority" # Breaks some display managers like lightdm and sddm
export NOTMUCH_CONFIG="$XDG_CONFIG_HOME/notmuch-config"
export GTK2_RC_FILES="$XDG_CONFIG_HOME/gtk-2.0/gtkrc-2.0"
export LESSHISTFILE="-"
export WGETRC="$XDG_CONFIG_HOME/wget/wgetrc"
# export INPUTRC="$XDG_CONFIG_HOME/.config/shell/inputrc"
export ZDOTDIR="$XDG_CONFIG_HOME/zsh"
# Might break pipewire (If it doesn't exist)
# export ALSA_CONFIG_PATH="$XDG_CONFIG_HOME/alsa/asoundrc"
# export GNUPGHOME="$XDG_CONFIG_HOME/.config/gnupg"
# export WINEPREFIX="$XDG_DATA_HOME/wineprefixes/default"
# export KODI_DATA="$XDG_DATA_HOME/kodi"
export PASSWORD_STORE_DIR="$XDG_DATA_HOME/password-store"
export TMUX_TMPDIR="$XDG_RUNTIME_DIR"
export ANDROID_SDK_HOME="$XDG_CONFIG_HOME/android"
export ANSIBLE_CONFIG="$XDG_CONFIG_HOME/ansible/ansible.cfg"
export UNISON="$XDG_DATA_HOME/unison"
export HISTFILE="$XDG_CONFIG_HOME/zsh/history"
export WEECHAT_HOME="$XDG_CONFIG_HOME/weechat"
export MBSYNCRC="$XDG_CONFIG_HOME/mbsync/config"
export ELECTRUMDIR="$XDG_DATA_HOME/electrum"
export PYTHONSTARTUP="$XDG_CONFIG_HOME/python/pythonrc"
# export _JAVA_OPTIONS=-Djava.util.prefs.userRoot="$XDG_CONFIG_HOME"/java
# Other program settings:
export DICS="/usr/share/stardict/dic/"
export SDCV_PAGER='less --quit-if-one-screen -RX'
export SUDO_ASKPASS="$HOME/.local/bin/misc/dmenupass"
export LESS=-R
export LESS_TERMCAP_mb="$(printf '%b' '[1;31m')"
export LESS_TERMCAP_md="$(printf '%b' '[1;36m')"
export LESS_TERMCAP_me="$(printf '%b' '[0m')"
export LESS_TERMCAP_so="$(printf '%b' '[01;44;33m')"
export LESS_TERMCAP_se="$(printf '%b' '[0m')"
export LESS_TERMCAP_us="$(printf '%b' '[1;32m')"
export LESS_TERMCAP_ue="$(printf '%b' '[0m')"
export LESSOPEN="| /usr/bin/highlight -O ansi %s 2>/dev/null"
export MOZ_USE_XINPUT2="1"		# Mozilla smooth scrolling/touchpads.
export AWT_TOOLKIT="MToolkit wmname LG3D"	#May have to install wmname
export _JAVA_AWT_WM_NONREPARENTING=1	# Fix for Java applications in dwm/bspwm
export QT_STYLE_OVERRIDE=adwaita-dark
export TRANSMISSION_DAEMON="transmission-daemon -w $XDG_DOWNLOAD_DIR/transmission --logfile $XDG_DATA_HOME/transmission/log"

[ ! -f $XDG_CONFIG_HOME/shell/shortcutrc ] && setsid shortcuts >/dev/null 2>&1


# Start graphical server on user's current tty if not already running and put the outputs into ~/.local/share/xorg/
[ "$(tty)" = "/dev/tty1" ] && ! pidof -s Xorg >/dev/null 2>&1 && exec startx "$XINITRC"

# Switch escape and caps if tty and no passwd required:
sudo -n loadkeys ${XDG_CONFIG_HOME:-$HOME/.config}/x11/ttymaps.kmap 2>/dev/null
