#!/bin/zsh

# Default programs:
export EDITOR="nvim"
export TERMINAL="st"
export BROWSER="firefox"
export VIDEO="mpv"
export IMAGE="nsxiv"

export MEDIA="/media"
export XDG_DOWNLOAD_DIR="$MEDIA"
export XDG_MUSIC_DIR="$MEDIA/music"
export XDG_VIDEOS_DIR="$MEDIA/videos"
export XDG_PICTURES_DIR="$MEDIA/pictures"
export XDG_DOCUMENTS_DIR="$MEDIA/documents"
export NOTES_DIR="$HOME/personal/notes"
export XDG_CONFIG_HOME="$HOME/.config"
export XDG_DATA_HOME="$HOME/.local/share"
export XDG_CACHE_HOME="$HOME/.cache"
export XRESOURCES="$XDG_CONFIG_HOME/x/xresources"
export XSESSION="$XDG_CONFIG_HOME/x/xsession"
#export XAUTHORITY="$XDG_RUNTIME_DIR/Xauthority" # Breaks some display managers like lightdm and sddm
export NOTMUCH_CONFIG="$XDG_CONFIG_HOME/notmuch-config"
export GTK2_RC_FILES="$XDG_CONFIG_HOME/gtk-2.0/gtkrc-2.0"
export LESS=-R
export LESSHISTFILE="-"
export WGETRC="$XDG_CONFIG_HOME/wget/wgetrc"
export ZDOTDIR="$XDG_CONFIG_HOME/zsh"
export XINITRC="$XDG_CONFIG_HOME/x/xinitrc"
export WINEPREFIX="$XDG_DATA_HOME/wineprefixes/default"
export KODI_DATA="$XDG_DATA_HOME/kodi"
export PASSWORD_STORE_DIR="$XDG_DATA_HOME/password-store"
export TMUX_TMPDIR="$XDG_RUNTIME_DIR"
export ANDROID_SDK_HOME="$XDG_CONFIG_HOME/android"
export ANSIBLE_CONFIG="$XDG_CONFIG_HOME/ansible/ansible.cfg"
export UNISON="$XDG_DATA_HOME/unison"
export WEECHAT_HOME="$XDG_CONFIG_HOME/weechat"
export MBSYNCRC="$XDG_CONFIG_HOME/mbsync/config"
export ELECTRUMDIR="$XDG_DATA_HOME/electrum"
export PYTHONSTARTUP="$XDG_CONFIG_HOME/python/pythonrc"
# export _JAVA_OPTIONS=-Djava.util.prefs.userRoot="$XDG_CONFIG_HOME"/java
# Other program settings:
export DICS="/usr/share/stardict/dic/"
export SDCV_PAGER='less --quit-if-one-screen -RX'
export SUDO_ASKPASS="$HOME/.local/bin/misc/dmenupass"
export MOZ_USE_XINPUT2="1"		# Mozilla smooth scrolling/touchpads.
export AWT_TOOLKIT="MToolkit wmname LG3D"	#May have to install wmname
export _JAVA_AWT_WM_NONREPARENTING=1	# Fix for Java applications in dwm/bspwm
# export QT_STYLE_OVERRIDE=adwaita-dark
export TRANSMISSION_DAEMON="transmission-daemon -w $XDG_DOWNLOAD_DIR/transmission --logfile $XDG_CACHE_HOME/transmission/log"

export JAVA_HOME=/usr/lib/jvm/default
export GOPATH="$XDG_DATA_HOME/go"
export GOMODCACHE="$XDG_CACHE_HOME/go/mod"
export CARGO_HOME="$XDG_DATA_HOME/cargo"
export NPM_PATH="$XDG_DATA_HOME/npm"
export FZF_DEFAULT_OPTS='--reverse'

export PATH="$PATH:$(find $HOME/.local/bin/ -type d -printf ":%p" ):$NPM_PATH/bin:$GOPATH/bin:$CARGO_HOME/bin:$JAVA_HOME/bin"

pipewire >/dev/null 2>&1&

# Start graphical server on user's current tty if not already running and put the outputs into ~/.local/share/xorg/
[ "$(tty)" = "/dev/tty1" ] && ! pidof -s Xorg >/dev/null 2>&1 && exec startx "$XINITRC"
#

[ ! -f $XDG_CONFIG_HOME/shell/shortcutrc ] && setsid shortcuts >/dev/null 2>&1

# Switch escape and caps if tty and no passwd required:
sudo -n loadkeys ${XDG_CONFIG_HOME:-$HOME/.config}/shell/ttymaps.kmap 2>/dev/null
