#!/bin/sh

xrdb ${XDG_CONFIG_HOME:-$HOME/.config}/x11/xresources & xrdbpid=$!
xautolock -time 10 -locker  'slock'&
redshift -l 31.77:35.23&
remaps &
emacs --daemon &

autostart="unclutter clipmenud sxhkd mpd dunst picom"

for program in $autostart; do
	pidof -s "$program" || "$program" &
done >/dev/null 2>&1

# Ensure that xrdb has finished running before moving on to start the WM/DE.
[ -n "$xrdbpid" ] && wait "$xrdbpid"
