vim.opt.bg = 'dark'
vim.cmd(('hi Visual  guifg=black gui=none'))
vim.cmd(('hi Pmenu guifg=yellow guibg=none'))
vim.cmd(('hi PmenuSel guifg=none'))
vim.cmd(('hi Normal ctermbg=NONE guibg=NONE '))
vim.cmd(('hi NormalFloat  guibg=none'))
vim.cmd(('hi SignColumn guibg=none '))
vim.cmd(('hi TabLine guibg=none '))
vim.cmd(('hi CursorLine guibg=#444444'))
vim.cmd(('hi CursorColumn guibg=#444444'))
