#!/bin/sh

xrdb ${XDG_CONFIG_HOME:-$HOME/.config}/x/xresources & xrdbpid=$!
xautolock -time 10 -locker 'physlock'&
redshift -l 31.77:35.23&
remaps &
emacs --daemon&
xsmon&
eval $TRANSMISSION_DAEMON&

autostart="clipmenud sxhkd mpd mpd_notify xbanish picom dunst pipewire"

for program in $autostart; do
	pidof -s "$program" || "$program" &
done >/dev/null 2>&1

# Ensure that xrdb has finished running before moving on to start the WM/DE.
[ -n "$xrdbpid" ] && wait "$xrdbpid"

exec openbox-session
