#!/bin/sh
# xrandr --output eDP-1  --mode "1024x768"&
xrdb ${XDG_CONFIG_HOME:-$HOME/.config}/x/xresources & xrdbpid=$!
xset s 600&
xss-lock -- physlock -s&
redshift -l 31.77:35.23&
remaps &
emacs --daemon&

autostart="clipmenud sxhkd mpd mpd_notify picom pipewire"


for program in $autostart; do
	pidof -s "$program" || "$program" &
done >/dev/null 2>&1

# Ensure that xrdb has finished running before moving on to start the WM/DE.
[ -n "$xrdbpid" ] && wait "$xrdbpid"

exec awesome
